config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root to: 'products#index'
  resources :products, only: [:new, :create, :destroy, :edit, :update]
  get "products/search", to: "products#search", as: :search_products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name, length: { minimum: 3 }
  validates :description, length: { minimum: 5 }
  validates :price, :amount, :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    category_name = Category.find(params[:id]).name
    @products = Product.where("category_id": params[:id])
    if @products.exists?
      flash[:notice] = "Showing all products from #{category_name} category"
    else
      flash[:error] = "No product found in #{category_name} category"
      redirect_to categories_path
    end
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    values = params.require(:category).permit(:name)
    @category = Category.new(values)
    if @category.save
      flash[:success] = "#{@category.name} was created"
      redirect_to categories_path
    else
      render :new
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    flash[:success] = "#{@category.name} was updated"
    redirect_to categories_path
  end

  def destroy
    category = Category.find(params[:id])
    product = Product.where("category_id": params[:id])
    if product.exists?
      flash[:error] = "Can't delete: there is a product in this category"
      redirect_to categories_path
    else
      Category.destroy(params[:id])
      flash[:success] = "#{category.name} was deleted"
      redirect_to categories_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def search
    @name = params[:name]
    @products = Product.where("name ilike ?", "%#{@name}%")
    if @products.exists?
      flash[:notice] = "Results for #{@name}"
    else
      flash[:error] = "No results for #{@name}"
    end
  end

  def new
     @product = Product.new
     @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "#{@product.name} was created"
      redirect_to root_path
    else
      render_view(:new)
    end
  end

  def edit
    render_view(:edit)
  end

  def update
    if @product.update(product_params)
      flash[:success] = "#{@product.name} was updated"
      redirect_to root_path
    else
      render_view(:new)
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "#{@product.name} was deleted"
    redirect_to root_path
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :amount, :category_id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def render_view(view)
    @categories = Category.all
    render view
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |form| %>
  <div class="row">
    <div class="col-sm-4">
      <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class:"form-control" %>
      </div>
    </div>
  </div>
  <%= form.submit button_name, class:"btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: "form", locals: { button_name: "Update" } %>

app/views/categories/index.html.erb
<%= flash_messages %>
<table class="table table-bordered table-hover">
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
         <td><%= link_to "Show category products", category,
          class: "btn btn-default"
        %></td>
        <td><%= link_to "Edit", edit_category_path(category),
          class: "btn btn-default"
        %></td>
        <td><%= button_to "Remove", category, method: :delete,
          class: "btn btn-danger", data: {
            confirm: "Remove #{category.name}?"}
        %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= button_to "New category", new_category_path, class: "btn btn-primary",
  method: :get
%>

app/views/categories/new.html.erb
<%= render partial: "form", locals: { button_name: "Create" } %>

app/views/categories/show.html.erb
<%= flash_messages %>
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Category</th>
    <th scope="col">Price</th>
    <th scope="col">Amount</th>
  </tr>
</thead>

  <tbody>
    <%= render @products %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Tech Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('computer.ico'), :rel => 'icon', :type => "image/x-icon" %>
  </head>

  <body>
    <%= nav_bar brand: "My Tech Store", brand_link: root_url do  %>
      <%= menu_group do %>
        <%= menu_item "Categories", categories_path %>
      <% end %>
      <%= form_tag search_products_path, method: :get,
        class: "navbar-form navbar-right"  do %>
        <div class="form-group">
          <%= text_field_tag :name, @name, class: "form-control" %>
          <%= button_to "Search", nil, class: "btn btn-default" %>
        </div>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <div class="card text-center footer navbar-fixed-bottom">
    <div>
      Developed with ❤ by: <a href="https://github.com/ayrtonaoki/" class="text-muted" target="_blank">Ayrton Aoki</a>
  </div>
</div>
</html>

app/views/products/_form.html.erb
<% @product.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
<% end %>
<%= form_for @product do |form| %>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class:"form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class:"form-control", rows: 4 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <div class="form-group">
          <%= form.label :category %>
          <%= form.collection_select :category_id, @categories, :id, :name, {}, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <div class="form-group">
          <%= form.label :price %>
          <%= form.number_field :price, class:"form-control", step:0.01 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <div class="form-group">
          <%= form.label :amount %>
          <%= form.number_field :amount, class:"form-control" %>
      </div>
    </div>
  </div>
  <%= form.submit button_name, class:"btn btn-primary" %>
<% end %>

app/views/products/_product.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td><%= product.category.name %></td>
  <td><%= "US$ #{product.price}" %></td>
  <td><%= product.amount %></td>
  <td><%= link_to "Edit", edit_product_path(product),
    class: "btn btn-default"
  %></td>
  <td><%= button_to "Remove", product, method: :delete,
    class: "btn btn-danger", data: {
      confirm: "Remove #{product.name}?"}
  %></td>
</tr>

app/views/products/_products_list_headers.html.erb
<thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Description</th>
    <th scope="col">Category</th>
    <th scope="col">Price</th>
    <th scope="col">Amount</th>
  </tr>
</thead>

app/views/products/index.html.erb
<%= flash_messages %>
<table class="table table-bordered table-hover">
  <%= render "products_list_headers" %>
  <tbody>
    <%= render @products %>
  </tbody>
</table>

<%= button_to "New product", new_product_path, method: :get, class: "btn btn-primary"  %>

app/views/products/search.html.erb
<%= flash_messages %>
<table class="table table-bordered table-hover">
  <%= render "products_list_headers" %>
  <tbody>
    <%= render @products %>
  </tbody>
</table>